### ISSUE TITLE
Couldn't run on Ubuntu 22.04 VM, got 'Segmentation Fault' on line 64 of midi.c

### ISSUE THREAD

**Issue by Hendo16** [wurlyfox/c1#2]
The compilation seemed to go through okay, however there were some warnings about midi.o, specifically:
<code>`src/pc/sound/midi.c: In function ‘SwMidiInit’:
`
`src/pc/sound/midi.c:163:14: warning: passing argument 3 of ‘fluid_sfloader_set_callbacks’ from `incompatible pointer type [-Wincompatible-pointer-types]
`
`  163 |     mem_open,mem_read,mem_seek,mem_tell,mem_close);
`
`     |              ^~~~~~~~
`
`     |              |
`
`     |              int (*)(void *, int,  void *)
`In file included from /usr/include/fluidsynth.h:102,
`
`                from src/pc/sound/midi.c:4:
`
`/usr/include/fluidsynth/sfont.h:174:40: note: expected ‘fluid_sfloader_callback_read_t’ {aka ‘int `(*)(void *, long long int,  void *)’} but argument is of type ‘int (*)(void *, int,  void *)’
`
`  174 |         fluid_sfloader_callback_read_t read,
`
`      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
`
`src/pc/sound/midi.c:163:23: warning: passing argument 4 of ‘fluid_sfloader_set_callbacks’ from `incompatible pointer type [-Wincompatible-pointer-types]
`
`  163 |     mem_open,mem_read,mem_seek,mem_tell,mem_close);
`
`      |                       ^~~~~~~~
`
`      |                       |
`
`      |                       int (*)(void *, long int,  int)
`
`In file included from /usr/include/fluidsynth.h:102,
`
`                from src/pc/sound/midi.c:4:
`
`/usr/include/fluidsynth/sfont.h:175:40: note: expected ‘fluid_sfloader_callback_seek_t’ {aka ‘int `(*)(void *, long long int,  int)’} but argument is of type ‘int (*)(void *, long int,  int)’
`
`  175 |         fluid_sfloader_callback_seek_t seek,
`
`      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
`
`src/pc/sound/midi.c:163:32: warning: passing argument 5 of ‘fluid_sfloader_set_callbacks’ from `incompatible pointer type [-Wincompatible-pointer-types]
`
`  163 |     mem_open,mem_read,mem_seek,mem_tell,mem_close);
`
`     |                                ^~~~~~~~
`
`      |                                |
`
`      |                                long int (*)(void *)
`
`In file included from /usr/include/fluidsynth.h:102,
`
`                 from src/pc/sound/midi.c:4:
`
`/usr/include/fluidsynth/sfont.h:176:40: note: expected ‘fluid_sfloader_callback_tell_t’ {aka ‘long long `int (*)(void *)’} but argument is of type ‘long int (*)(void *)’
`
`  176 |         fluid_sfloader_callback_tell_t tell,
`
`      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
`</code>

And when I run 'c1' in gdb I get this
<code>`Thread 1 "c1" received signal SIGSEGV, Segmentation fault.
`
`0x566313fb in mem_read (buf=0xffffcc8c, count=8, handle=0x0) at src/pc/sound/midi.c:64
`
`64	  memcpy(buf, stream->p, count);
</code>

**Comment by ManDude** [comment]
What is the result of `sizeof(void*)`?

**Comment by Hendo16** [comment]
Nevermind, I figured out the issue

Went into pc/sound/midi.c and took a look at the problamatic struct's based off of the warnings it was giving off during compilation and updated the structs to be 'long long' where it needed to be instead of just 'long' (in mem_read and mem_seek's parameters and in the return type of mem_tell)

Compiles and runs just fine with music. Originally, I just did mem_read and it ran fine but without music.
